#!/bin/bash
<<COMMENT
PRIME NUMBERS HAVE TWO FACTORS 1 AND THE SAME NUMBER , 
THUS 1 IS UNITY WHICH IS NEITHER PRIME NOR COPRIME AND FOLLOWS THE RULES OF THE STRUCTURE UNITY , BECAUSE 1 HAS ONLY ONE  FACTOR.
2 IS PRIME BY DEFINITION, 3 IS ALSO PRIME WITH TWO FACTORS 1 AND 3 . 4 IS NOT A PRIME NUMBER. 4 WITH THREE FACTORS 1,2,4 . 
COMMENT
